import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useDispatch, useSelector } from 'react-redux';
import { RootState } from '../store/reducers';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
	const dispatch = useDispatch();
	const { counter } = useSelector((state: RootState) => state.counter);

	function increment() {
		dispatch({
			type: 'INCREMENT',
		});
	}

	function decrement() {
		dispatch({
			type: 'DECREMENT',
		});
	}

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<h1>{counter}</h1>

			<button onClick={increment}>+</button>
			<button onClick={decrement}>-</button>
			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{' '}
					<span className={styles.logo}>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
};

export default Home;
