import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Header from '../components/Header';
import { useAppDispatch, useAppSelector } from '../store/hooks';
import { selectCount } from '../store/selectors';
import { decrement, increment } from '../store/actions/counterActions';

const Home: NextPage = () => {
	const dispatch = useAppDispatch();
	const counterValue = useAppSelector(selectCount);

	function incrementCounter() {
		dispatch(increment());
	}

	function decrementCounter() {
		dispatch(decrement());
	}

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header>{counterValue}</Header>

			<button onClick={incrementCounter}>+</button>
			<button onClick={decrementCounter}>-</button>
			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{' '}
					<span className={styles.logo}>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
};

export default Home;
